CREATE SEQUENCE SEQ_BOARD;

CREATE TABLE TBL_BOARD(
    BNO NUMBER(10,0),
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(2000) NOT NULL,
    WRITER VARCHAR2(50) NOT NULL,
    REGDATE DATE DEFAULT SYSDATE,
    UPDATEDATE DATE DEFAULT SYSDATE
);

ALTER TABLE TBL_BOARD ADD CONSTRAINT PK_BOARD
PRIMARY KEY(BNO);

DESC TBL_BOARD;

INSERT INTO TBL_BOARD(BNO, TITLE, CONTENT, WRITER)
VALUES(SEQ_BOARD.NEXTVAL, '오이' , '파프리카', '토마토');

SELECT * FROM TBL_BOARD WHERE BNO > 0 ORDER BY BNO DESC;

INSERT INTO TBL_BOARD (BNO, TITLE, CONTENT, WRITER)
    (SELECT SEQ_BOARD.NEXTVAL, TITLE, CONTENT, WRITER FROM TBL_BOARD);

COMMIT;

SELECT * FROM TBL_BOARD ORDER BY BNO+1 DESC;

--실행계획. 인덱스 + 힌트
--ASC : 오름차순, DESC : 내림차순
SELECT * FROM TBL_BOARD ORDER BY BNO DESC;

SELECT /*INDEX_ASC(TBL_BOARD PK_BOARD)*/ *
FROM TBL_BOARD WHERE BNO>0;

SELECT ROWNUM, BNO, TITLE, WRITER
FROM TBL_BOARD
WHERE ROWNUM <=20;

SELECT BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDATE
      FROM (
         SELECT /*+ INDEX_DESC(TBL_BOARD PK_BOARD) */
         ROWNUM RN, BNO, TITLE,CONTENT, WRITER,REGDATE, UPDATEDATE
         FROM TBL_BOARD
         WHERE ROWNUM <= 20
      )
WHERE RN >10;