DESC DEPT;
DESC EMP;
DESC BONUS;
DESC SALGRADE;

SELECT * FROM DEPT;
SELECT * FROM EMP;
SELECT * FROM BONUS;
SELECT * FROM SALGRADE;

/*263p Q4*/
--1. 서브쿼리 활용 시 단일행 함수 사용
SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
AND E.SAL > (
    SELECT MAX(SAL)
    FROM EMP
    WHERE JOB = 'SALESMAN'
)
ORDER BY EMPNO;

--2. 서브쿼리 활용 시 다중행 함수 사용
SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
AND E.SAL > ALL (
    SELECT SAL
    FROM EMP
    WHERE JOB = 'SALESMAN'
)
ORDER BY EMPNO;

/*239p*/
--Q1
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM DEPT D, EMP E
WHERE D.DEPTNO = E.DEPTNO AND E.SAL > 2000
ORDER BY D.DEPTNO, E.EMPNO;

--Q2 (MADE BY ME)
SELECT D.DEPTNO, D.DNAME,
    FLOOR(AVG(E.SAL)) AS AVG_SAL,
    MAX(E.SAL) AS MAX_SAL,
    MIN(E.SAL) AS MIN_SAL,
    COUNT(E.EMPNO) AS CNT
FROM DEPT D, EMP E
WHERE D.DEPTNO = E.DEPTNO
GROUP BY D.DEPTNO, D.DNAME;

--Q2 (MADE BY TEACHER)
SELECT D.DEPTNO, D.DNAME,
    TRUNC(AVG(E.SAL), 0) AS AVG_SAL,
    MAX(E.SAL) AS MAX_SAL,
    MIN(E.SAL) AS MIN_SAL,
    COUNT(E.EMPNO) AS CNT
FROM DEPT D, EMP E
WHERE D.DEPTNO = E.DEPTNO
GROUP BY D.DEPTNO, D.DNAME;

--Q3
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
FROM DEPT D, EMP E
WHERE D.DEPTNO = E.DEPTNO
ORDER BY D.DEPTNO, D.DNAME;

--Q4
SELECT D.DEPTNO, D.DNAME, EE.EMPNO, EE.ENAME, EE.MGR, EE.SAL
     , EM.DEPTNO AS DEPTNO_1, S.LOSAL, S.HISAL, S.GRADE
     , EM.EMPNO AS MGR_EMPNO, EM.ENAME AS MGR_ENAME
FROM DEPT D, EMP EE, EMP EM, SALGRADE S
WHERE EE.SAL BETWEEN S.LOSAL(+) AND S.HISAL(+)
      AND D.DEPTNO = EE.DEPTNO(+)
      AND EE.MGR = EM.EMPNO(+)
ORDER BY D.DEPTNO, EE.EMPNO;
