CREATE TABLE TBL_REPLY (
    RNO NUMBER(10, 0),
    BNO NUMBER(10, 0) NOT NULL,
    REPLY VARCHAR(1000) NOT NULL,
    REPLYER VARCHAR(50) NOT NULL,
    REPLYDATE DATE DEFAULT SYSDATE,
    UPDATEDATE DATE DEFAULT SYSDATE,
);

CREATE SEQUENCE SEQ_REPLY;

ALTER TABLE TBL_REPLY ADD CONSTRAINT PK_REPLY PRIMARY KEY (RNO);

ALTER TABLE TBL_REPLY ADD CONSTRAINT FK_REPLY_BOARD
FOREIGN KEY (BNO) REFERENCES TBL_BOARD(BNO);