USE db0416;

CREATE TABLE SEOUL_LOCATION(
	NO INT,
    NAME VARCHAR(100),
    ADDRESS VARCHAR(200),
    POSTER VARCHAR(200),
    MSG VARCHAR(1000), 
    PRIMARY KEY(NO)
);

DESC SEOUL_LOCATION;
SELECT * FROM SEOUL_LOCATION;

CREATE TABLE SEOUL_NATURE(
	NO INT,
    NAME VARCHAR(100),
    ADDRESS VARCHAR(200),
    POSTER VARCHAR(200),
    MSG VARCHAR(1000), 
    PRIMARY KEY(NO)
);

DESC SEOUL_NATURE;
SELECT * FROM SEOUL_NATURE;

CREATE TABLE SEOUL_HOTEL(
	NO INT,
    NAME VARCHAR(100),
    SCORE DOUBLE,
    ADDRESS VARCHAR(200),
    POSTER VARCHAR(200),
    IMAGES VARCHAR(1000),
    PRIMARY KEY(NO)
);

DESC SEOUL_HOTEL;
SELECT * FROM SEOUL_HOTEL;

COMMIT;