CREATE TABLE EMP_DDL(
    EMPNO NUMBER(4),
    ENAME VARCHAR(10),
    JOB VARCHAR(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7, 2),
    COMM NUMBER(7, 2),
    DEPTNO NUMBER(2)
);

DESC EMP_DDL;
SELECT * FROM EMP_DDL;

CREATE TABLE DEPT_DDL AS SELECT * FROM DEPT;

SELECT * FROM DEPT_DDL;

CREATE TABLE EMP_DDL_30
AS SELECT * FROM EMP
WHERE DEPTNO = 30;

SELECT * FROM EMP_DDL_30;

CREATE TABLE EMPDEPT_DDL
AS SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE,
          E.SAL, E.COMM, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE 1 <> 1;

DESC EMPDEPT_DDL;
SELECT * FROM EMPDEPT_DDL;

CREATE TABLE EMP_ALTER AS SELECT * FROM EMP;

DESC EMP_ALTER;
SELECT * FROM EMP_ALTER;

ALTER TABLE EMP_ALTER
ADD HP VARCHAR2(20);

ALTER TABLE EMP_ALTER
RENAME COLUMN HP TO TEL;

ALTER TABLE EMP_ALTER
MODIFY EMPNO NUMBER(5);

ALTER TABLE EMP_ALTER
DROP COLUMN TEL;

RENAME EMP_ALTER TO EMP_RENAME;

DESC EMP_RENAME;
SELECT * FROM EMP_RENAME;

--아래의 문장을 실수로 실행해서 데이터가 날라갔을 땐
DELETE FROM EMP_RENAME;
--당황하지 말고 롤백할 것
ROLLBACK;
--근데 이건 롤백 해도 안먹힘 개위험함
TRUNCATE TABLE EMP_RENAME;



