--다중 서브쿼리
SELECT EMPLOYEE_ID, MAX(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, EMPLOYEE_ID;

SELECT * FROM EMPLOYEES
WHERE SALARY IN (
    SELECT MAX(SALARY)
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID
)
ORDER BY SALARY;

SELECT * FROM EMPLOYEES
WHERE SALARY NOT IN (
    SELECT MAX(SALARY)
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID
)
ORDER BY SALARY;

SELECT *
FROM EMPLOYEES
WHERE EXISTS ( /*TRUE -> 데이터가 전부 출력됨*/
    SELECT *
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID=100
);

SELECT *
FROM EMPLOYEES
WHERE EXISTS ( /*FALSE -> 아무 데이터도 출력되지 않음*/
    SELECT *
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID=700
);

SELECT *
FROM EMPLOYEES
WHERE SALARY <> ANY(600, 10000, 12000);

SELECT *
FROM EMPLOYEES
WHERE SALARY < ANY (
    SELECT SALARY
    FROM EMPLOYEES
    WHERE HIRE_DATE > '08/01/01'
);

/*  DEPARTMENTS 테이블에서 DEPARTMENT_NAME이 'IT'인 DEPARTMENT_ID와 일치하는
    EMPLOYEES 테이블의 FIRST_NAME, LAST_NAME, JOB_ID, SALARY를 조회 */
SELECT FIRST_NAME, LAST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID
    FROM DEPARTMENTS
    WHERE DEPARTMENT_NAME = 'IT'
);

/*  LOCATIONS 테이블에서 STATE_PROVINCE가 'California'인 LOCATION_ID와 일치하는
    DEPARTMENTS 테이블의 DEPARTMENT_ID, DEPARTMENT_NAME을 조회   */
SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS
WHERE LOCATION_ID IN (
    SELECT LOCATION_ID
    FROM LOCATIONS
    WHERE STATE_PROVINCE = 'California'
);

/*  COUNTRIES 테이블에서 REGION_ID가 3인 COUNTRY_ID가 포함된 LOCATIONS 테이블의
    CITY, STATE_PROVINCE, STREET_ADDRESS를 조회    */
SELECT CITY, STATE_PROVINCE, STREET_ADDRESS
FROM LOCATIONS
WHERE COUNTRY_ID IN (
    SELECT COUNTRY_ID
    FROM COUNTRIES
    WHERE REGION_ID = 3
);
