CREATE TABLE BOARD (
    NUM NUMBER(5) PRIMARY KEY,
    PASS VARCHAR2(30),
    NAME VARCHAR2(30),
    EMAIL VARCHAR2(30),
    TITLE VARCHAR2(50),
    CONTENT VARCHAR2(1000),
    READCOUNT NUMBER(4) DEFAULT 0,
    WRITEDATE DATE DEFAULT SYSDATE
);

DESC BOARD;

CREATE SEQUENCE BOARD_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO BOARD(NUM, NAME, EMAIL, PASS, TITLE, CONTENT)
VALUES(BOARD_SEQ.NEXTVAL, '¼ºÀ±Á¤', 'pinksung@nate.com', '1234'
    , 'Ã¹¹æ¹®', '¹Ý°©½À´Ï´Ù.');
INSERT INTO BOARD(NUM, NAME, EMAIL, PASS, TITLE, CONTENT)
VALUES(BOARD_SEQ.NEXTVAL, '¼ºÀ±Á¤', 'pinksung@nate.com', '1234'
    , '±è¹ä', '¸ÀÀÖ¾î¿ä.');
INSERT INTO BOARD(NUM, NAME, EMAIL, PASS, TITLE, CONTENT)
VALUES(BOARD_SEQ.NEXTVAL, 'Àü¼öºó', 'raccon@nate.com', '3333'
    , '°íµî¾Ö', 'ÀÏ½ÄÀÔ´Ï´Ù.');
INSERT INTO BOARD(NUM, NAME, EMAIL, PASS, TITLE, CONTENT)
VALUES(BOARD_SEQ.NEXTVAL, 'Àü¿øÁö', 'one@nate.com', '1111'
    , '°¹°ñ¸¶À»', 'µÅÁö»ï°ã»ìÀÌ ¸ÀÀÖ½À´Ï´Ù.');

SELECT * FROM BOARD;

COMMIT;
